### PR TITLE
Add shasums + minor edits

### PR DESCRIPTION
**Pull request by Strykar**
1. Added sha256sums for `*.deb`, please add the checksum for `flashback.patch`, it's not available yet on here.
2. Changed URL and cleaned up irrelevant notes from the previous template. Some similar cruft still remains like on lines `139-141`.

Boy O boy, this is a lot of packages...

### CODE REVIEW

**Comment by Strykar** [comment]
With the latest squash, it builds here: ==> Finished making: regolith-de 1.4.1-1 (Tue 09 Jun 2020 03:39:46 AM IST)

**Comment by gardotd426** [comment]
All was good aside from the obvious problem of it not building otherwise, lol. Merged

**Comment by gardotd426** [comment]
@Strykar check out the dev branch, which I created for us to tinker with, and to try out methodology for cleaning up the PKGBUILD.

What do you think of the new URL scheme? Best I could think of (at least so far). Created the new dev branch for stuff like this, so we don't have to keep reverting shit.

**Comment by gardotd426** [comment]
https://github.com/gardotd426/regolith-de/tree/dev

**Pull request merged**
